name: Release

on: workflow_dispatch

jobs:
  build:
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-20.04
            runtime: linux-x64
            ext: ""
          - name: Windows
            os: windows-latest
            runtime: win-x64
            ext: ".exe"

    env:
      proj: "Tkmm.Desktop"
      launcher: "Tkmm.Launcher"

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Publish TKMM
        shell: bash
        run: |
          dotnet publish src/${{ env.proj }}/${{ env.proj }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          --version-suffix ${{ github.event.release.tag_name }} \
          -o ${{ matrix.config.name }} \
          -p:Version=${{ github.event.release.tag_name }}

      - name: Rename executable
        shell: bash
        run: |
          mv \
          ${{ matrix.config.name }}/Tkmm.Desktop${{ matrix.config.ext }} \
          ${{ matrix.config.name }}/tkmm${{ matrix.config.ext }}

      - name: Archive Build Files
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: ../TKMM-${{ matrix.config.runtime }}.zip
          directory: ${{ matrix.config.name }}
          path: ./**

      - name: Upload artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: TKMM-${{ matrix.config.runtime }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish TKMM Launcher
        shell: bash
        run: |
          dotnet publish src/${{ env.launcher }}/${{ env.launcher }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          --version-suffix ${{ github.event.release.tag_name }} \
          -o Launcher/${{ matrix.config.name }} \
          -p:Version=1.0.0

      - name: Archive Build Files
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: ../../TKMM-Launcher-${{ matrix.config.runtime }}.zip
          directory: Launcher/${{ matrix.config.name }}
          path: ./**

      - name: Upload artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: TKMM-Launcher-${{ matrix.config.runtime }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
